# Generated by Django 4.2.25 on 2025-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
