# Generated by Django 4.2.25 on 2025-10-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='nickname',
        ),
    ]
